name: gtc_env
channels:
  - defaults
dependencies:
  - anaconda
  - git
  - h5netcdf
  - h5py
  - ipympl
  - matplotlib
  - netcdf4
  - numpy
  - pre_commit
  - python=3.11.5
  - pytorch
  - scikit-learn
  - seaborn
  - torchvision
  - tqdm
  - xarray
  - gluonts
  - bokeh
  - conda-build
